import { useState, useEffect } from 'react';
import { LanguageContext } from './LanguageContext';

const translations = {
    en: {
        loginTitle: 'Hello',
        loginSubtitle: 'Sign in to access your dashboard',
        emailAddress: 'Email Address',
        email: 'Email',
        password: 'Password',
        signIn: 'Sign In',
        logout: 'Logout',
        employeeSpace: 'Employee Space',
        dashboardTitle: 'Dashboard',
        dashboardSubtitle: 'Submit and track your claims and incidents',
        reportIncident: 'Report a New Incident',
        ticketTitle: 'Title',
        category: 'Category',
        department: 'Department',
        priority: 'Priority',
        description: 'Description',
        sendTicket: 'Send Ticket',
        
        // File & Attachment translations
        fichierJoint: 'Attachment (File)',
        attachment: 'Attachment',
        attachments: 'Attachments',
        file: 'File',
        uploadFile: 'Upload a file',
        chooseFile: 'Choose file',
        noFileChosen: 'No file chosen',
        dragAndDropFile: 'Drag and drop your file here, or browse',
        download: 'Download',

        // Comments & Actions
        comments: 'Comments',
        writeComment: 'Write a comment...',
        sendComment: 'Send Comment',
        send: 'Send',
        closeTicket: 'Close Ticket',
        ticketClosedSuccessfully: 'Ticket closed successfully',
        noComments: 'No comments yet.',

        ticketHistory: 'My Tickets History',
        ticketHistorySubtitle: 'Check the progress of your requests',
        searchPlaceholder: 'Search by title, ID or center...',
        allStatuses: 'All statuses',
        allCategories: 'All categories',
        allDepartments: 'All departments',
        actions: 'Actions',
        details: 'Details',
        close: 'Close',
        successTicketCreated: 'Ticket created successfully!',
        errorGeneric: 'An error occurred.',
        technicianSpace: 'Technical Support',
        technicianTitle: 'Technician Space',
        technicianSubtitle: 'Supervise and process reported technical incidents',
        techSpace: 'Tech Space',
        TECHSPACE: 'Tech Space',
        adminSpace: 'Administrator Space',
        ADMINSPACE: 'Administrator Space',
        adminDashboardTitle: 'Administrator Dashboard',
        adminDashboardSubtitle: 'Global system supervision, technician and center management',
        totalUsers: 'Total Users',
        resolvedTickets: 'Resolved / Closed Tickets',
        totalTickets: 'Total Tickets',
        toProcess: 'To Process / In Progress',
        resolved: 'Resolved',
        ticketQueue: 'Incident Queue',
        ticketQueueSubtitle: 'Manage the lifecycle of each technical ticket',
        noTicketsFound: 'No tickets found',
        selectCategory: 'Select category',
        selectDepartment: 'Select department',
        selectPriority: 'Select priority',
        status: 'Status / Enable-Disable',
        id: 'ID',
        titlePlaceholder: 'Enter ticket title...',
        descriptionPlaceholder: 'Describe your issue in detail...',
        createdBy: 'Created by',
        displayedCount: 'displayed',

        // System Tickets & Centers
        systemTickets: 'Global Ticket Management',
        systemTicketsSubtitle: 'View, filter, and update the status of all system tickets',
        center: 'Center',
        selectCenter: 'Select Center',
        allCenters: 'All Centers',
        CENTRE: 'Center',
        Centre: 'Center',
        centre: 'Center',

        // Notifications & Lists
        notifications: 'Notifications',
        markAllAsRead: 'Mark all as read',
        noNotifications: 'No notifications',
        newNotification: 'New notification',
        newTicket: 'New ticket',
        usersListTitle: 'Users List',
        usersListSubtitle: 'Manage registered users and permissions',

        // User Management translations
        userManagementTitle: 'User Account Management',
        userManagementSubtitle: 'Enable or disable system employees and technicians',
        closeUserManagement: 'Close User Management',
        openUserManagement: 'Open User Management',
        employeeTechnicianList: 'List of Employees & Technicians',
        manageUserAccess: 'Manage user account access',
        registeredUsersCount: 'registered users',
        fullName: 'Full Name',
        role: 'Role',
        active: 'Active',
        disabled: 'Disabled',
        deactivate: 'Deactivate',
        activate: 'Activate',
        noUsersFound: 'No users found',

        // Roles & UI specific terms
        ADMIN: 'Administrator',
        ADMINISTRATEUR: 'Administrator',
        Administrateur: 'Administrator',
        TECHNICIEN: 'Technician',
        TECHNICIAN: 'Technician',
        Technicien: 'Technician',
        TECHNICIEN_IT: 'IT Technician',
        TECHNICIAN_IT: 'IT Technician',
        'Technicien IT': 'IT Technician',
        EMPLOYE: 'Employee',
        EMPLOYEE: 'Employee',
        Employe: 'Employee',
        Employé: 'Employee',
        Employés: 'Employees',

        // Categories & Departments
        HARDWARE: 'Hardware',
        SOFTWARE: 'Software',
        WEBSITE: 'Website',
        SITE_WEB: 'Web Site',
        NETWORK: 'Network',
        NETWORKING: 'Networking',
        RESEAUX: 'Networks',
        RESEAU: 'Network',
        MAINTENANCE: 'Maintenance',
        MAINTENANCE_INFORMATIQUE: 'IT Maintenance',
        AUTRE: 'Other',
        OTHER: 'Other',

        // Departments & Custom Keys
        IT: 'IT Department',
        HR: 'Human Resources',
        FINANCE: 'Finance',
        SUPPORT: 'Support',
        UNCATEGORIZED: 'Uncategorized',
        DEPT_IT: 'IT & Network Department',
        DEPT_MAINTENANCE: 'Technical & Maintenance',
        DEPT_ADMINISTRATION: 'Administration & Academic Affairs',
        
        'Administration': 'Administration',
        'Informatique': 'IT Department',
        'Technique': 'Technical Department',
        'TECHS': 'Technical',
        'TECH': 'Technical',
        'Ressources Humaines': 'Human Resources',

        NOUVEAU_NON_VU: 'New (Unseen)',
        NOUVEAU_VU: 'New (Seen)',
        EN_COURS: 'In Progress',
        RESOLU: 'Resolved',
        FERME: 'Closed',
        NEW_UNSEEN: 'New (Unseen)',
        NEW_SEEN: 'New (Seen)',
        IN_PROGRESS: 'In Progress',
        RESOLVED: 'Resolved',
        CLOSED: 'Closed',

        BASSE: 'Low',
        MOYENNE: 'Medium',
        HAUTE: 'High',
        URGENTE: 'Urgent',
        LOW: 'Low',
        MEDIUM: 'Medium',
        HIGH: 'High',
        URGENT: 'Urgent',

        nouveau: '+ New',
        'Nouveau': '+ New',
        '+ Nouveau': '+ New',
        'Nouveau +': '+ New',
        actif: 'Active',
        'Actif': 'Active',
        afficher: 'Show',
        'Afficher': 'Show',
        show: 'Show',
        cancel: 'Cancel',
        create: 'Create',
        none: 'None',
        unknownUser: 'Unknown User',
        writeCommentPlaceholder: 'Write a comment...',
        techniciansCount: 'Active Technicians',
        techsButtonTitle: 'Technician Management',
        techniciansRegistered: 'registered technicians',
        techPerformanceTitle: 'Technician Activity Reports',
        techPerformanceSubtitle: 'Click on a technician to manage their centers, response times, and password',
        specialite: 'Specialty',
        specialtyPlaceholder: 'e.g., Regional Support',
        'ex: Support Régional': 'e.g., Regional Support',
        assignedTicketsCount: 'Assigned Tickets',
        resolvedTicketsCount: 'Resolved / Closed',
        pendingTicketsCount: 'In progress',
        deactivated: 'Deactivated',
        noTechniciansFound: 'No technician accounts found',
        centersButtonTitle: 'Center Management',
        centersRegistered: 'registered centers',
        centersManagementTitle: 'Centers List & Created Tickets',
        centersManagementSubtitle: 'Click on a center to view details, change its password, or delete it',
        centreName: 'Center Name',
        codeBureau: 'Office Code',
        technicianAssigned: 'Assigned Technician',
        ticketsCreatedCount: 'Created Tickets',
        noCentersFound: 'No centers found',
        createUserButtonTitle: 'Create User',
        createNewUser: 'Create a new user',
        nom: 'Last Name',
        prenom: 'First Name',
        techniciansAndEmployees: 'Technicians & Employees',
        'Techniciens & Employés': 'Technicians & Employees',
        'إصدار مستخدم جديد': 'Create a new user',
        'إنشاء مستخدم جديد': 'Create a new user',
        'عدد التقنيين': 'Active Technicians',
        'التقنيون': 'Technicians',
        'التذاكر المحلولة': 'Resolved / Closed Tickets',
        'إجمالي التذاكر': 'Total Tickets',

        // Password change translations & Extra Admin keys
        changePassword: 'Change my password',
        changePasswordTitle: 'Change password for',
        currentPassword: 'Current Password',
        newPassword: 'New password',
        newPasswordPlaceholder: 'Enter new password',
        confirmPassword: 'Confirm Password',
        confirmNewPassword: 'Confirm New Password',
        save: 'Save',
        saveChanges: 'Save Changes',
        passwordsDoNotMatch: 'New passwords do not match.',
        passwordChangedSuccess: 'Password updated successfully!',
        password: 'Password',
        changePasswordButton: 'Change Password',

        // Sections
        section01: 'Section 01',
        section02: 'Section 02',
        section03: 'Section 03',

        // Newly added snippet translations
        codeCentre: 'Center Code',
        codeCentreTitle: 'Center Code',
        centerPassword: 'Center Password',
        motDePasseDuCentre: 'Center Password',
        changerLeMotDePasse: 'Change password',
        ticketsEmisParCeCentre: 'Tickets issued by this center',
        aucunTicketEnregistrePourCeCentre: 'No tickets registered for this center.',
        supprimerLeCentre: 'Delete Center',
        confirmDeleteCenter: 'Are you sure you want to permanently delete this center?',
        centreAssigneACeTechnicien: 'Center assigned to this technician',
        removeCenterTooltip: 'Remove this center',
        aucunCentreRattachePourLeMoment: 'No center attached yet.',
        selectionnerUnCentreAAssigner: 'Select a center to assign...',
        attribuer: 'Assign',
        assignButton: 'Assign',
        ticketsAssignesEtTempsDeReponse: 'Assigned Tickets & Response Time',
        resolutionTimeTooltip: 'Time elapsed from opening to resolution',
        noAssignedTickets: 'No assigned tickets at the moment.',
        nomField: 'Last Name',
        prenomField: 'First Name',
        temporaryPassword: 'Temporary Password',
        motDePasseProvisoire: 'Temporary Password',
        roleField: 'Role',
        roleTechnician: 'IT Technician',
        roleCenter: 'Center',
        roleAdmin: 'Administrator',
        centreAssocie: 'Associated Center',
        noCenter: 'No center',
        aucunCentre: 'No center',
        annuler: 'Cancel',
        creerLUtilisateur: 'Create User',
        createUserSubmit: 'Create User',
        errorCreatingUser: 'Error creating user.',
        regionalSupport: 'Regional Support',
        noneText: 'None',

        // Newly requested exact key mappings
        ticketsCreatedByCenter: 'Tickets created by this center',
        noTicketsForCenter: 'No tickets registered for this center.',
        deleteCenterButton: 'Delete Center',
        assignedCenterToTech: 'Center assigned to this technician',
        assignedCentersToTech: 'Assigned Centers to Technician',
        deleteUser: 'Delete User',
        responseTime: 'Response Time',
        noCenterAttached: 'No center attached yet.',
        assignedTicketsAndTime: 'Assigned Tickets & Response Time',
        selectCenterToAssign: 'Select a center to assign...',
        // Additional interface labels
        CurrentPassword: 'Current password', 'N/A': 'N/A', addCenter: 'Add center',
        assignedTechnician: 'Assigned technician', associatedCenter: 'Associated center',
        back: 'Back', changePasswordFor: 'Change password for', confirmDeleteTicket: 'Are you sure you want to delete this ticket?',
        confirmDeleteUser: 'Are you sure you want to delete this user?', day: 'Day', deleteTicket: 'Delete ticket',
        errorCredentials: 'Invalid email or password', firstName: 'First name', lastName: 'Last name',
        loading: 'Loading...', oldPassword: 'Current password', passwordUpdatedSuccessfully: 'Password updated successfully',
        passwordsDontMatch: 'Passwords do not match', resolvedShort: 'Resolved', sendReply: 'Send reply',
        technician: 'Technician', today: 'Today', unassigned: 'Unassigned', user: 'User',
        averageResponseTime: 'Average response time', responseTime24h: 'Response time (24h)',
        noResponseData: 'No response-time data available', hours: 'hours', minutes: 'minutes'
    },
    fr: {
        loginTitle: 'Bonjour',
        loginSubtitle: 'Connectez-vous pour accéder à votre tableau de bord',
        emailAddress: 'Adresse e-mail',
        email: 'E-mail',
        password: 'Mot de passe',
        signIn: 'Se connecter',
        logout: 'Déconnexion',
        employeeSpace: 'Espace Employé',
        dashboardTitle: 'Tableau de Bord',
        dashboardSubtitle: 'Soumettez et suivez vos réclamations et incidents',
        reportIncident: 'Signaler un Nouvel Incident',
        ticketTitle: 'Titre',
        category: 'Catégorie',
        department: 'Département',
        priority: 'Priorité',
        description: 'Description',
        sendTicket: 'Envoyer le Ticket',
        
        fichierJoint: 'Pièce jointe',
        attachment: 'Pièce jointe',
        attachments: 'Pièces jointes',
        file: 'Fichier',
        uploadFile: 'Téléverser un fichier',
        chooseFile: 'Choisir un fichier',
        noFileChosen: 'Aucun fichier choisi',
        dragAndDropFile: 'Glissez-déposez votre fichier ici, ou parcourez',
        download: 'Télécharger',

        comments: 'Commentaires',
        writeComment: 'Écrire un commentaire...',
        sendComment: 'Envoyer le commentaire',
        send: 'Envoyer',
        closeTicket: 'Fermer le ticket',
        ticketClosedSuccessfully: 'Ticket fermé avec succès',
        noComments: 'Aucun commentaire pour le moment.',

        ticketHistory: 'Historique de mes Tickets',
        ticketHistorySubtitle: "Consultez l'état d'avancement de vos demandes",
        searchPlaceholder: 'Rechercher par titre, ID ou centre...',
        allStatuses: 'Tous les statuts',
        allCategories: 'Toutes les catégories',
        allDepartments: 'Tous les départements',
        actions: 'Actions',
        details: 'Détails',
        close: 'Fermer',
        successTicketCreated: 'Ticket créé avec succès !',
        errorGeneric: 'Une erreur est survenue.',
        technicianSpace: 'Support Technique',
        technicianTitle: 'Espace Technicien',
        technicianSubtitle: 'Supervisez et traitez les incidents techniques signalés',
        techSpace: 'Espace Tech',
        TECHSPACE: 'Espace Tech',
        adminSpace: 'Espace Administrateur',
        ADMINSPACE: 'Espace Administrateur',
        adminDashboardTitle: 'Tableau de bord Administrateur',
        adminDashboardSubtitle: 'Supervision globale du système, gestion des techniciens et des centres',
        totalUsers: 'Total Utilisateurs',
        resolvedTickets: 'Tickets Résolus / Fermés',
        totalTickets: 'Total Tickets',
        toProcess: 'À Traiter / En Cours',
        resolved: 'Résolus',
        ticketQueue: "File d'Attente des Incidents",
        ticketQueueSubtitle: 'Gérez le cycle de vie de chaque ticket technique',
        noTicketsFound: 'Aucun ticket trouvé',
        selectCategory: 'Sélectionner une catégorie',
        selectDepartment: 'Sélectionner un département',
        selectPriority: 'Sélectionner une priorité',
        status: 'État / Activer-Désactiver',
        id: 'ID',
        titlePlaceholder: 'Entrez le titre du ticket...',
        descriptionPlaceholder: 'Décrivez votre problème en détail...',
        createdBy: 'Créé par',
        displayedCount: 'affichés',

        systemTickets: 'Gestion globale des tickets',
        systemTicketsSubtitle: 'Consultez, filtrez et mettez à jour le statut de tous les tickets du système',
        center: 'Centre',
        selectCenter: 'Sélectionner un centre',
        allCenters: 'Tous les centres',
        CENTRE: 'Centre',
        Centre: 'Centre',
        centre: 'Centre',

        notifications: 'Notifications',
        markAllAsRead: 'Tout marquer comme lu',
        noNotifications: 'Aucune notification',
        newNotification: 'Nouvelle notification',
        newTicket: 'Nouveau ticket',
        usersListTitle: 'Liste des utilisateurs',
        usersListSubtitle: 'Gérez les utilisateurs enregistrés et leurs autorisations',

        userManagementTitle: 'Gestion des Comptes Utilisateurs',
        userManagementSubtitle: 'Activer ou désactiver les employés et techniciens du système',
        closeUserManagement: 'Fermer la gestion des utilisateurs',
        openUserManagement: "Ouvrir la gestion des utilisateurs",
        employeeTechnicianList: 'Liste des Employés & Techniciens',
        manageUserAccess: "Gérez l'accès des comptes utilisateurs",
        registeredUsersCount: 'utilisateurs enregistrés',
        fullName: 'Nom & Prénom',
        role: 'Rôle',
        active: 'Actif',
        disabled: 'Désactivé',
        deactivate: 'Désactiver',
        activate: 'Activer',
        noUsersFound: 'Aucun utilisateur trouvé',

        ADMIN: 'Administrateur',
        ADMINISTRATEUR: 'Administrateur',
        Administrateur: 'Administrateur',
        TECHNICIEN: 'Technicien',
        TECHNICIAN: 'Technicien',
        Technicien: 'Technicien',
        TECHNICIEN_IT: 'Technicien IT',
        TECHNICIAN_IT: 'Technicien IT',
        'Technicien IT': 'Technicien IT',
        EMPLOYE: 'Employé',
        EMPLOYEE: 'Employé',
        Employe: 'Employé',
        Employé: 'Employé',
        Employés: 'Employés',

        HARDWARE: 'Matériel',
        SOFTWARE: 'Logiciel',
        WEBSITE: 'Site Web',
        SITE_WEB: 'Site Web',
        NETWORK: 'Réseau',
        NETWORKING: 'Réseautage',
        RESEAUX: 'Réseaux',
        RESEAU: 'Réseau',
        MAINTENANCE: 'Maintenance',
        MAINTENANCE_INFORMATIQUE: 'Maintenance Informatique',
        AUTRE: 'Autre',
        OTHER: 'Autre',

        IT: 'Informatique',
        HR: 'Ressources Humaines',
        FINANCE: 'Finance',
        SUPPORT: 'Support',
        UNCATEGORIZED: 'Non catégorisé',
        DEPT_IT: 'Département Informatique & Réseau',
        DEPT_MAINTENANCE: 'Technique & Maintenance',
        DEPT_ADMINISTRATION: 'Administration & Affaires Académiques',

        'Administration': 'Administration',
        'Informatique': 'Informatique',
        'Technique': 'Technique',
        'TECHS': 'Technique',
        'TECH': 'Technique',
        'Ressources Humaines': 'Ressources Humaines',

        NOUVEAU_NON_VU: 'Nouveau (Non vu)',
        NOUVEAU_VU: 'Nouveau (Vu)',
        EN_COURS: 'En cours',
        RESOLU: 'Résolu',
        FERME: 'Fermé',
        NEW_UNSEEN: 'Nouveau (Non vu)',
        NEW_SEEN: 'Nouveau (Vu)',
        IN_PROGRESS: 'En cours',
        RESOLVED: 'Résolu',
        CLOSED: 'Fermé',

        BASSE: 'Basse',
        MOYENNE: 'Moyenne',
        HAUTE: 'Haute',
        URGENTE: 'Urgente',
        LOW: 'Basse',
        MEDIUM: 'Moyenne',
        HIGH: 'Haute',
        URGENT: 'Urgente',

        nouveau: '+ Nouveau',
        'Nouveau': '+ Nouveau',
        '+ Nouveau': '+ Nouveau',
        'Nouveau +': '+ Nouveau',
        actif: 'Actif',
        'Actif': 'Actif',
        afficher: 'Afficher',
        'Afficher': 'Afficher',
        show: 'Afficher',
        cancel: 'Annuler',
        create: 'Créer',
        none: 'Aucun',
        unknownUser: 'Utilisateur inconnu',
        writeCommentPlaceholder: 'Écrire un commentaire...',
        techniciansCount: 'Techniciens Actifs',
        techsButtonTitle: 'Gestion des Techniciens',
        techniciansRegistered: 'techniciens enregistrés',
        techPerformanceTitle: "Rapports d'activité des Techniciens",
        techPerformanceSubtitle: 'Cliquez sur un technicien pour gérer ses centres, ses temps de réponse et son mot de passe',
        specialite: 'Spécialité',
        specialtyPlaceholder: 'ex: Support Régional',
        'ex: Support Régional': 'ex: Support Régional',
        assignedTicketsCount: 'Tickets Assignés',
        resolvedTicketsCount: 'Résolus / Fermés',
        pendingTicketsCount: 'En cours',
        deactivated: 'Désactivé',
        noTechniciansFound: 'Aucun compte technicien trouvé',
        centersButtonTitle: 'Gestion des Centres',
        centersRegistered: 'centres enregistrés',
        centersManagementTitle: 'Liste des Centres & Tickets Créés',
        centersManagementSubtitle: 'Cliquez sur un centre pour voir ses détails, modifier son mot de passe ou le supprimer',
        centreName: 'Nom du Centre',
        codeBureau: 'Code Bureau',
        technicianAssigned: 'Technicien Référent',
        ticketsCreatedCount: 'Tickets Créés',
        noCentersFound: 'Aucun centre trouvé',
        createUserButtonTitle: 'Créer Utilisateur',
        createNewUser: 'Créer un nouvel utilisateur',
        nom: 'Nom',
        prenom: 'Prénom',
        techniciansAndEmployees: 'Techniciens & Employés',
        'Techniciens & Employés': 'Techniciens & Employés',
        'إصدار مستخدم جديد': 'Créer un nouvel utilisateur',
        'إنشاء مستخدم جديد': 'Créer un nouvel utilisateur',
        'عدد التقنيين': 'Techniciens Actifs',
        'التقنيون': 'Techniciens',
        'التذاكر المحلولة': 'Tickets Résolus / Fermés',
        'إجمالي التذاكر': 'Total Tickets',

        // Password change translations
        changePassword: 'Modifier mon mot de passe',
        changePasswordTitle: 'Changer le mot de passe',
        currentPassword: 'Ancien mot de passe',
        newPassword: 'Nouveau mot de passe',
        newPasswordPlaceholder: 'Entrez le nouveau mot de passe',
        confirmPassword: 'Confirmer le mot de passe',
        confirmNewPassword: 'Confirmer le nouveau mot de passe',
        save: 'Enregistrer',
        saveChanges: 'Enregistrer les modifications',
        passwordsDoNotMatch: 'Les nouveaux mots de passe ne correspondent pas.',
        passwordChangedSuccess: 'Mot de passe mis à jour avec succès !',
        password: 'Mot de passe',
        changePasswordButton: 'Changer le mot de passe',

        // Sections
        section01: 'Section 01',
        section02: 'Section 02',
        section03: 'Section 03',

        // Newly added snippet translations
        codeCentre: 'Code Centre',
        codeCentreTitle: 'Code Centre',
        centerPassword: 'Mot de passe du Centre',
        motDePasseDuCentre: 'Mot de passe du Centre',
        changerLeMotDePasse: 'Changer le mot de passe',
        ticketsEmisParCeCentre: 'Tickets émis par ce centre',
        aucunTicketEnregistrePourCeCentre: 'Aucun ticket enregistré pour ce centre.',
        supprimerLeCentre: 'Supprimer le centre',
        confirmDeleteCenter: 'Êtes-vous sûr de vouloir supprimer définitivement ce centre ?',
        centreAssigneACeTechnicien: 'Centre assigné à ce technicien',
        removeCenterTooltip: 'Retirer ce centre',
        aucunCentreRattachePourLeMoment: 'Aucun centre rattaché pour le moment.',
        selectionnerUnCentreAAssigner: 'Sélectionner un centre à assigner...',
        attribuer: 'Attribuer',
        assignButton: 'Attribuer',
        ticketsAssignesEtTempsDeReponse: 'Tickets assignés & Temps de réponse',
        resolutionTimeTooltip: "Temps écoulé de l'ouverture à la résolution",
        noAssignedTickets: 'Aucun ticket assigné pour le moment.',
        nomField: 'Nom',
        prenomField: 'Prénom',
        temporaryPassword: 'Mot de passe provisoire',
        motDePasseProvisoire: 'Mot de passe provisoire',
        roleField: 'Rôle',
        roleTechnician: 'Technicien IT',
        roleCenter: 'Centre',
        roleAdmin: 'Administrateur',
        centreAssocie: 'Centre associé',
        noCenter: 'Aucun centre',
        aucunCentre: 'Aucun centre',
        annuler: 'Annuler',
        creerLUtilisateur: "Créer l'utilisateur",
        createUserSubmit: "Créer l'utilisateur",
        errorCreatingUser: "Erreur lors de la création de l'utilisateur.",
        regionalSupport: 'Support Régional',
        noneText: 'Aucun',

        // Newly requested exact key mappings
        ticketsCreatedByCenter: 'Tickets émis par ce centre',
        noTicketsForCenter: 'Aucun ticket enregistré pour ce centre.',
        deleteCenterButton: 'Supprimer le centre',
        assignedCenterToTech: 'Centre assigné à ce technicien',
        assignedCentersToTech: 'Centres assignés au technicien',
        deleteUser: 'Supprimer l\'utilisateur',
        responseTime: 'Temps de réponse',
        noCenterAttached: 'Aucun centre rattaché pour le moment.',
        assignedTicketsAndTime: 'Tickets assignés & Temps de réponse',
        selectCenterToAssign: 'Sélectionner un centre à assigner...',
        // Libellés supplémentaires de l’interface
        CurrentPassword: 'Mot de passe actuel', 'N/A': 'N/D', addCenter: 'Ajouter un centre',
        assignedTechnician: 'Technicien assigné', associatedCenter: 'Centre associé',
        back: 'Retour', changePasswordFor: 'Changer le mot de passe de', confirmDeleteTicket: 'Voulez-vous vraiment supprimer ce ticket ?',
        confirmDeleteUser: 'Voulez-vous vraiment supprimer cet utilisateur ?', day: 'Jour', deleteTicket: 'Supprimer le ticket',
        errorCredentials: 'E-mail ou mot de passe incorrect', firstName: 'Prénom', lastName: 'Nom',
        loading: 'Chargement...', oldPassword: 'Mot de passe actuel', passwordUpdatedSuccessfully: 'Mot de passe mis à jour avec succès',
        passwordsDontMatch: 'Les mots de passe ne correspondent pas', resolvedShort: 'Résolu', sendReply: 'Envoyer la réponse',
        technician: 'Technicien', today: 'Aujourd’hui', unassigned: 'Non assigné', user: 'Utilisateur',
        averageResponseTime: 'Temps de réponse moyen', responseTime24h: 'Temps de réponse (24 h)',
        noResponseData: 'Aucune donnée de temps de réponse disponible', hours: 'heures', minutes: 'minutes'
    },
    ar: {
        loginTitle: 'مرحباً',
        loginSubtitle: 'تسجيل الدخول للوصول إلى لوحة التحكم الخاصة بك',
        emailAddress: 'البريد الإلكتروني',
        email: 'البريد الإلكتروني',
        password: 'كلمة المرور',
        signIn: 'تسجيل الدخول',
        logout: 'تسجيل الخروج',
        employeeSpace: 'فضاء الموظف',
        dashboardTitle: 'لوحة التحكم',
        dashboardSubtitle: 'قم بتقديم ومتابعة طلباتك بلاغاتك',
        reportIncident: 'الإبلاغ عن حادث جديد',
        ticketTitle: 'العنوان',
        category: 'الفئة',
        department: 'القسم',
        priority: 'الأولوية',
        description: 'الوصف',
        sendTicket: 'إرسال التذكرة',
        
        fichierJoint: 'الملف المرفق',
        attachment: 'مرفق',
        attachments: 'المرفقات',
        file: 'ملف',
        uploadFile: 'رفع ملف',
        chooseFile: 'اختر ملفاً',
        noFileChosen: 'لم يتم اختيار أي ملف',
        dragAndDropFile: 'قم بسحب وإفلات الملف هنا، أو تصفح الجهاز',
        download: 'تحميل',

        comments: 'التعليقات',
        writeComment: 'اكتب تعليقاً...',
        sendComment: 'إرسال التعليق',
        send: 'إرسال',
        closeTicket: 'إغلاق التذكرة',
        ticketClosedSuccessfully: 'تم إغلاق التذكرة بنجاح',
        noComments: 'لا توجد تعليقات حتى الآن.',
        
        ticketHistory: 'سجل تذاكري',
        ticketHistorySubtitle: 'تحقق من تقدم طلباتك',
        searchPlaceholder: 'البحث بالعنوان، المعرف أو المركز...',
        allStatuses: 'جميع الحالات',
        allCategories: 'جميع الفئات',
        allDepartments: 'جميع الأقسام',
        actions: 'الإجراءات',
        details: 'التفاصيل',
        close: 'إغلاق',
        successTicketCreated: 'تم إنشاء التذكرة بنجاح!',
        errorGeneric: 'حدث خطأ ما.',
        technicianSpace: 'الدعم الفني',
        technicianTitle: 'فضاء التقني',
        technicianSubtitle: 'الإشراف على الحوادث التقنية المبلغ عنها ومعالجتها',
        techSpace: 'الفضاء التقني',
        TECHSPACE: 'الفضاء التقني',
        adminSpace: 'فضاء المسؤول',
        ADMINSPACE: 'فضاء المسؤول',
        adminDashboardTitle: 'لوحة تحكم المسؤول',
        adminDashboardSubtitle: 'الإشراف الشامل على النظام، إدارة التقنيين والمراكز',
        totalUsers: 'إجمالي المستخدمين',
        resolvedTickets: 'التذاكر المحلولة / المغلقة',
        totalTickets: 'إجمالي التذاكر',
        toProcess: 'قيد المعالجة / قيد التنفيذ',
        resolved: 'تم الحل',
        ticketQueue: 'قائمة انتظار الحوادث',
        ticketQueueSubtitle: 'إدارة دورة حياة كل تذكرة تقنية',
        noTicketsFound: 'لم يتم العثور على أي تذاكر',
        selectCategory: 'اختر الفئة',
        selectDepartment: 'اختر القسم',
        selectPriority: 'اختر الأولوية',
        status: 'الحالة / تفعيل-تعطيل',
        id: 'المعرف',
        titlePlaceholder: 'أدخل عنوان التذكرة...',
        descriptionPlaceholder: 'صف مشكلتك بالتفصيل...',
        createdBy: 'أنشئت بواسطة',
        displayedCount: 'معروض',

        systemTickets: 'إدارة التذاكر الشاملة',
        systemTicketsSubtitle: 'عرض، تصفية وتحديث حالة جميع تذاكر النظام',
        center: 'المركز',
        selectCenter: 'اختر المركز',
        allCenters: 'جميع المراكز',
        CENTRE: 'المركز',
        Centre: 'المركز',
        centre: 'المركز',

        notifications: 'الإشعارات',
        markAllAsRead: 'تحديد الكل كمقروء',
        noNotifications: 'لا توجد إشعارات',
        newNotification: 'إشعار جديد',
        newTicket: 'تذكرة جديدة',
        usersListTitle: 'قائمة المستخدمين',
        usersListSubtitle: 'إدارة المستخدمين المسجلين والصلاحيات',

        userManagementTitle: 'إدارة حسابات المستخدمين',
        userManagementSubtitle: 'تفعيل أو تعطيل موظفي وتقنيي النظام',
        closeUserManagement: 'إغلاق إدارة المستخدمين',
        openUserManagement: 'فتح إدارة المستخدمين',
        employeeTechnicianList: 'قائمة الموظفين والتقنيين',
        manageUserAccess: 'إدارة صلاحيات الوصول لحسابات المستخدمين',
        registeredUsersCount: 'مستخدم مسجل',
        fullName: 'الاسم الكامل',
        role: 'الدور',
        active: 'نشط',
        disabled: 'معطل',
        deactivate: 'تعطيل',
        activate: 'تفعيل',
        noUsersFound: 'لم يتم العثور على مستخدمين',

        ADMIN: 'مسؤول النظام',
        ADMINISTRATEUR: 'مسؤول النظام',
        Administrateur: 'مسؤول النظام',
        TECHNICIEN: 'تقني',
        TECHNICIAN: 'تقني',
        Technicien: 'تقني',
        TECHNICIEN_IT: 'تقني IT',
        TECHNICIAN_IT: 'تقني IT',
        'Technicien IT': 'تقني IT',
        EMPLOYE: 'موظف',
        EMPLOYEE: 'موظف',
        Employe: 'موظف',
        Employé: 'موظف',
        Employés: 'الموظفون',

        HARDWARE: 'أجهزة عتادية',
        SOFTWARE: 'برمجيات',
        WEBSITE: 'موقع إلكتروني',
        SITE_WEB: 'موقع إلكتروني',
        NETWORK: 'شبكات',
        NETWORKING: 'شبكات',
        RESEAUX: 'شبكات',
        RESEAU: 'شبكة',
        MAINTENANCE: 'صيانة',
        MAINTENANCE_INFORMATIQUE: 'صيانة الحاسوب والأنظمة',
        AUTRE: 'أخرى',
        OTHER: 'أخرى',

        IT: 'تكنولوجيا المعلومات',
        HR: 'الموارد البشرية',
        FINANCE: 'المالية',
        SUPPORT: 'الدعم الفني',
        UNCATEGORIZED: 'غير مصنف',
        DEPT_IT: 'قسم تكنولوجيا المعلومات والشبكات',
        DEPT_MAINTENANCE: 'قسم التقنية والصيانة',
        DEPT_ADMINISTRATION: 'قسم الإدارة والشؤون الأكاديمية',

        'Administration': 'الإدارة',
        'Informatique': 'الإعلام الآلي',
        'Technique': 'القسم التقني',
        'TECHS': 'القسم التقني',
        'TECH': 'القسم التقني',
        'Ressources Humaines': 'الموارد البشرية',

        NOUVEAU_NON_VU: 'جديد (غير مرئي)',
        NOUVEAU_VU: 'جديد (مرئي)',
        EN_COURS: 'قيد التنفيذ',
        RESOLU: 'تم الحل',
        FERME: 'مغلق',
        NEW_UNSEEN: 'جديد (غير مرئي)',
        NEW_SEEN: 'جديد (مرئي)',
        IN_PROGRESS: 'قيد التنفيذ',
        RESOLVED: 'تم الحل',
        CLOSED: 'مغلق',

        BASSE: 'منخفضة',
        MOYENNE: 'متوسطة',
        HAUTE: 'عالية',
        URGENTE: 'عاجلة',
        LOW: 'منخفضة',
        MEDIUM: 'متوسطة',
        HIGH: 'عالية',
        URGENT: 'عاجلة',

        nouveau: '+ جديد',
        'Nouveau': '+ جديد',
        '+ Nouveau': '+ جديد',
        'Nouveau +': '+ جديد',
        actif: 'نشط',
        'Actif': 'نشط',
        afficher: 'عرض',
        'Afficher': 'عرض',
        show: 'عرض',
        cancel: 'إلغاء',
        create: 'إنشاء',
        none: 'لا شيء',
        unknownUser: 'مستخدم مجهول',
        writeCommentPlaceholder: 'اكتب تعليقاً...',
        techniciansCount: 'التقنيون النشطون',
        techsButtonTitle: 'إدارة التقنيين',
        techniciansRegistered: 'تقني مسجل',
        techPerformanceTitle: 'تقارير نشاط التقنيين',
        techPerformanceSubtitle: 'انقر على أي تقني لإدارة مراكزه، أوقات الاستجابة وكلمة المرور',
        specialite: 'التخصص',
        specialtyPlaceholder: 'مثال: الدعم الإقليمي',
        'ex: Support Régional': 'مثال: الدعم الإقليمي',
        assignedTicketsCount: 'التذاكر المعينة',
        resolvedTicketsCount: 'المحلولة / المغلقة',
        pendingTicketsCount: 'قيد التنفيذ',
        deactivated: 'معطل',
        noTechniciansFound: 'لم يتم العثور على حسابات تقنيين',
        centersButtonTitle: 'إدارة المراكز',
        centersRegistered: 'مركز مسجل',
        centersManagementTitle: 'قائمة المراكز والتذاكر المنشأة',
        centersManagementSubtitle: 'انقر على مركز لعرض تفاصيله، تغيير كلمة المرور أو حذفه',
        centreName: 'اسم المركز',
        codeBureau: 'رمز المكتب',
        technicianAssigned: 'التقني المسؤول',
        ticketsCreatedCount: 'التذاكر المنشأة',
        noCentersFound: 'لم يتم العثور على مراكز',
        createUserButtonTitle: 'إنشاء مستخدم',
        createNewUser: 'إنشاء مستخدم جديد',
        nom: 'اللقب',
        prenom: 'الإسم',
        techniciansAndEmployees: 'التقنيون والموظفون',
        'Techniciens & Employés': 'التقنيون والموظفون',
        'إصدار مستخدم جديد': 'إنشاء مستخدم جديد',
        'إنشاء مستخدم جديد': 'إنشاء مستخدم جديد',
        'عدد التقنيين': 'التقنيون النشطون',
        'التقنيون': 'التقنيون',
        'التذاكر المحلولة': 'التذاكر المحلولة / المغلقة',
        'إجمالي التذاكر': 'إجمالي التذاكر',

        // Password change translations
        changePassword: 'تغيير كلمة المرور الخاصة بي',
        changePasswordTitle: 'تغيير كلمة المرور',
        currentPassword: 'كلمة المرور الحالية',
        newPassword: 'كلمة المرور الجديدة',
        newPasswordPlaceholder: 'أدخل كلمة المرور الجديدة',
        confirmPassword: 'تأكيد كلمة المرور',
        confirmNewPassword: 'تأكيد كلمة المرور الجديدة',
        save: 'حفظ',
        saveChanges: 'حفظ التغييرات',
        passwordsDoNotMatch: 'كلمتا المرور الجديدتان غير متطابقتين.',
        passwordChangedSuccess: 'تم تحديث كلمة المرور بنجاح!',
        password: 'كلمة المرور',
        changePasswordButton: 'تغيير كلمة المرور',

        // Sections
        section01: 'القسم 01',
        section02: 'القسم 02',
        section03: 'القسم 03',

        // Newly added snippet translations
        codeCentre: 'رمز المركز',
        codeCentreTitle: 'رمز المركز',
        centerPassword: 'كلمة مرور المركز',
        motDePasseDuCentre: 'كلمة مرور المركز',
        changerLeMotDePasse: 'تغيير كلمة المرور',
        ticketsEmisParCeCentre: 'التذاكر الصادرة عن هذا المركز',
        aucunTicketEnregistrePourCeCentre: 'لا توجد تذاكر مسجلة لهذا المركز.',
        supprimerLeCentre: 'حذف المركز',
        confirmDeleteCenter: 'هل أنت متأكد أنك تريد حذف هذا المركز نهائياً؟',
        centreAssigneACeTechnicien: 'المركز المعين لهذا التقني',
        removeCenterTooltip: 'إزالة هذا المركز',
        aucunCentreRattachePourLeMoment: 'لا يوجد مركز مرتبط في الوقت الحالي.',
        selectionnerUnCentreAAssigner: 'اختر مركزاً لتخصيصه...',
        attribuer: 'تخصيص',
        assignButton: 'تخصيص',
        ticketsAssignesEtTempsDeReponse: 'التذاكر المعينة ووقت الاستجابة',
        resolutionTimeTooltip: 'الوقت المنقضي من الفتح حتى الحل',
        noAssignedTickets: 'لا توجد تذاكر معينة في الوقت الحالي.',
        nomField: 'اللقب',
        prenomField: 'الاسم',
        temporaryPassword: 'كلمة المرور المؤقتة',
        motDePasseProvisoire: 'كلمة المرور المؤقتة',
        roleField: 'الدور',
        roleTechnician: 'تقني IT',
        roleCenter: 'مركز',
        roleAdmin: 'مسؤول النظام',
        centreAssocie: 'المركز المرتبط',
        noCenter: 'لا يوجد مركز',
        aucunCentre: 'لا يوجد مركز',
        annuler: 'إلغاء',
        creerLUtilisateur: 'إنشاء المستخدم',
        createUserSubmit: 'إنشاء المستخدم',
        errorCreatingUser: 'حدث خطأ أثناء إنشاء المستخدم.',
        regionalSupport: 'الدعم الإقليمي',
        noneText: 'لا شيء',

        // Newly requested exact key mappings
        ticketsCreatedByCenter: 'التذاكر الصادرة عن هذا المركز',
        noTicketsForCenter: 'لا توجد تذاكر مسجلة لهذا المركز.',
        deleteCenterButton: 'حذف المركز',
        assignedCenterToTech: 'المركز المعين لهذا التقني',
        assignedCentersToTech: 'المراكز المعينة للتقني',
        deleteUser: 'حذف المستخدم',
        responseTime: 'وقت الاستجابة',
        noCenterAttached: 'لا يوجد مركز مرتبط في الوقت الحالي.',
        assignedTicketsAndTime: 'التذاكر المعينة ووقت الاستجابة',
        selectCenterToAssign: 'اختر مركزاً لتخصيصه...',
        // تسميات إضافية للواجهة
        CurrentPassword: 'كلمة المرور الحالية', 'N/A': 'غير متاح', addCenter: 'إضافة مركز',
        assignedTechnician: 'التقني المعيّن', associatedCenter: 'المركز المرتبط',
        back: 'رجوع', changePasswordFor: 'تغيير كلمة المرور لـ', confirmDeleteTicket: 'هل أنت متأكد من حذف هذه التذكرة؟',
        confirmDeleteUser: 'هل أنت متأكد من حذف هذا المستخدم؟', day: 'اليوم', deleteTicket: 'حذف التذكرة',
        errorCredentials: 'البريد الإلكتروني أو كلمة المرور غير صحيحة', firstName: 'الاسم', lastName: 'اللقب',
        loading: 'جارٍ التحميل...', oldPassword: 'كلمة المرور الحالية', passwordUpdatedSuccessfully: 'تم تحديث كلمة المرور بنجاح',
        passwordsDontMatch: 'كلمتا المرور غير متطابقتين', resolvedShort: 'تم الحل', sendReply: 'إرسال الرد',
        technician: 'تقني', today: 'اليوم', unassigned: 'غير معيّن', user: 'مستخدم',
        averageResponseTime: 'متوسط وقت الاستجابة', responseTime24h: 'وقت الاستجابة (24 ساعة)',
        noResponseData: 'لا تتوفر بيانات عن وقت الاستجابة', hours: 'ساعات', minutes: 'دقائق'
    }
};

export function LanguageProvider({ children }) {
    const [locale, setLocale] = useState(() => localStorage.getItem('app_lang') || 'fr');

    useEffect(() => {
        localStorage.setItem('app_lang', locale);
        document.documentElement.dir = locale === 'ar' ? 'rtl' : 'ltr';
        document.documentElement.lang = locale;
    }, [locale]);

    const t = (key) => {
        if (!key) return '';
        const stringKey = key.toString().trim();
        const lowerKey = stringKey.toLowerCase();

        if (translations[locale]?.[stringKey] !== undefined) {
            return translations[locale][stringKey];
        }

        const currentDict = translations[locale];
        if (currentDict) {
            for (const dictKey in currentDict) {
                if (dictKey.toLowerCase() === lowerKey) {
                    return currentDict[dictKey];
                }
            }
        }

        if (translations['en'][stringKey] !== undefined) {
            return translations['en'][stringKey];
        }

        const enDict = translations['en'];
        if (enDict) {
            for (const dictKey in enDict) {
                if (dictKey.toLowerCase() === lowerKey) {
                    return enDict[dictKey];
                }
            }
        }

        return key;
    };

    const formatId = (id) => {
        if (!id) return '';
        if (locale === 'ar') {
            const num = Number(id);
            if (!isNaN(num)) {
                return num.toLocaleString('ar-EG');
            }
        }
        return id;
    };

    return (
        <LanguageContext.Provider value={{ locale, setLocale, t, formatId }}>
            {children}
        </LanguageContext.Provider>
    );
}

export default LanguageProvider;